### PR TITLE
add multi-color highlight support

### PR DESCRIPTION
**Pull request by kinalmehta**
Solves #13 

- Update readme with reference of multi-color highlight
- update license to include license of original highlight repo and its reference

> If you're fixing a UI issue, make sure you take two screenshots. One that shows the actual bug and another that shows how you fixed it.

### CODE REVIEW

**Comment by SlyBouhafs** [comment]
Hey @kinalmehta 
Can you add a screenshot of the new feature?
Thanks a lot for the contribution!

**Comment by kinalmehta** [comment]
What you're saying is correct. Just adding the CSS support for colours should ideally work. But it seems the repo I linked is no longer maintained and is not present in the logseq plugins marketplace. So I had to add it to this repo itself. 

[This](https://github.com/LeonWong0609/D42ker-Logseq) is another theme which supports colorful highlight but even here you have to manually set it up instead of directly installing from logseq marketplace. 

Hope this makes sense.

Thanks

**Comment by kinalmehta** [comment]
Hey. Just got to know that the highlight plugin will be uploaded to marketplace in few weeks.
So maybe just adding proper color cas would be a better way to do it as you said earlier.

I'll update the PR to do that once the highlight plugin is available on marketplace.

**Comment by SlyBouhafs** [comment]
Hey @kinalmehta Any updates?

**Comment by kinalmehta** [comment]
Hey @SlyBouhafs,

The original author has still not pushed the highlight plugin on logseq-marketplace.
Any suggestion from your side on how to proceed?

Thanks

**Pull request closed without merging**
